export const appActions = {
  //Authentication
  GET_USER: "GET_USER",
  LOGIN: "LOGIN",
  SIGN_UP: "SIGN_UP",
  FORGET_PASSWORD: "FORGET_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  LOGOUT: "LOGOUT",
  EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
  RESEND_EMAIL_VERIFICATION: "RESEND_EMAIL_VERIFICATION",
  OPEN_CANDIDATE_LISTS: "OPEN_CANDIDATE_LISTS",
  OPEN_COMPANY_PROFILE: "OPEN_COMPANY_PROFILE",
  JOB_LISTS: "JOB_LISTS",
  GET_USER:"GET_USER",
  GET_ADMIN_COURSE:"GET_ADMIN_COURSE",
  ADD_ADMIN_COURSE:"ADD_ADMIN_COURSE",
  UPDATE_ADMIN_COURSE:"UPDATE_ADMIN_COURSE",
  GET_MODULE_ACTION:'GET_MODULE_ACTION',
  GET_QUETIONS_ACTION:"GET_QUETIONS_ACTION",
  ADD_ADMIN_MODULE:  'ADD_ADMIN_MODULE',
  UPDATE_ADMIN_MODULE:'UPDATE_ADMIN_MODULE',
  ADD_ADMIN_QUESTION:"ADD_ADMIN_QUESTION",
  UPDATE_ADMIN_QUESTION:"UPDATE_ADMIN_QUESTION",
  DELETE_ADMIN_QUESTION:"DELETE_ADMIN_QUESTION",

  // admin
  STUDENT_REGSITER:"STUDENT_REGSITER",
  STUDENT_LISTS:"STUDENT_LISTS",
  UPDATE_STUDENT:"UPDATE_STUDENT",
  DELETE_STUDENT:"DELETE_STUDENT",
  ADD_CENTRE:"ADD_CENTRE",
  GET_CENTRE:"GET_CENTRE",
  UPDATE_CENTRE:"UPDATE_CENTRE",
  DELETE_CENTRE:"DELETE_CENTRE",
  // common
  UPLOAD_IMAGE:"UPLOAD_IMAGE",
  CLEAR_IMAGE:"CLEAR_IMAGE",


  // student
  GET_STUDENT_COURSE:"GET_STUDENT_COURSE",
  START_TEST:"START_TEST",
  UPDATE_TEST_ACTIVTY:"UPDATE_TEST_ACTIVTY",
  SAVE_RESULT:"SAVE_RESULT"
};
